### ISSUE TITLE
Error response from daemon: configured logging driver does not support reading

### ISSUE THREAD

**Issue by eleaner** [githubixx/ansible-role-docker#6]
Hi,

I am not sure if it has anything to do with this ansible role, but I cannot figure out what is wrong.
I had a bunch of docker nodes connected into swarm but decided to re-purpose them and build kuberenetes on them - using your tutorials.

When I got to the worker part, I realised that I have to remove docker from each of my nodes, install flannel and reinstall docker using your role. The new docker is also lower version than the previous one. 
So I did.

The kubernetes cluster seems to be working, but I realised that "docker logs" responds with:
`Error response from daemon: configured logging driver does not support reading`

my docker info confirms that I am using log-driver journald
and I cannot find any reason why would it behave this way.

maybe you have an idea?

Thanks in advance
Marcin

**Comment by eleaner** [comment]
it looks like probably the problem is in the binary 18.06.1-ce (although I did not check another one)
in theory, both "journald" and "json-file" should work with "docker logs."
Apparently, however,  journald can fail with the above message if docker is compiled without a libsystemd-dev present in the system

that's just theory because I did not check all possible combinations
it seems to be working with json-file, and this is what I am going to use for now.

**Comment by githubixx** [comment]
I'm using json logging so I can't really comment on this, sorry. I always try to stick with the latest version recommended/validated in the Kubernetes changelog and for K8s 1.13 it is 18.06.1-ce. But you can of course try a different version if you think it is a Docker problem (which is could be of course). According to https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#external-dependencies you can use `1.11.1, 1.12.1, 1.13.1, 17.03, 17.06, 17.09, 18.06`. But I guess even 18.09 will work it's just not validated yet. 

Have you tried `syslog` driver? Maybe this causes the logs to also show up in the systemd journal. If I execute `echo "test entry" | logger -t test` on a Ubuntu 18 host I can see the log entry with `journalctl -n 20`. `logger` is normally logging to syslog and I guess it will be just forwarded to systemd journal so maybe that works also with docker.
